name: Notify Telegram on PR Merge

on:
  pull_request:
    types:
      - closed

jobs:
  notify:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Notification
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          curl -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" \
          -H "Content-Type: application/json" \
          -d @- <<EOF
          {
            "chat_id": "$TELEGRAM_CHAT_ID",
            "text": "Pull Request Merged 🎉\nOrganization: ${{ github.organization }}\nRepository: ${{ github.repository }}\nPR Title: ${{ github.event.pull_request.title }}\nMerged by: ${{ github.event.pull_request.merged_by.login }}"
          }
          EOF
