name: Notify Telegram

on:
  workflow_call:
    inputs:
      TELEGRAM_BOT_TOKEN:
        required: true
        type: string
      TELEGRAM_CHAT_ID:
        required: true
        type: string
      TELEGRAM_TOPIC_ID:
        required: false
        type: string

jobs:
  send-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Notification
        env:
          TELEGRAM_BOT_TOKEN: ${{ inputs.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ inputs.TELEGRAM_CHAT_ID }}
          TELEGRAM_TOPIC_ID: ${{ inputs.TELEGRAM_TOPIC_ID }}
        run: |
          curl -s -X POST https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage \
            -H "Content-Type: application/json" \
            -d '{
              "chat_id": "'$TELEGRAM_CHAT_ID'",
              "message_thread_id": '$TELEGRAM_TOPIC_ID',
              "text": "Notification from reusable workflow",
              "parse_mode": "Markdown"
            }'
